### ISSUE TITLE
`useField` error for non-object `updateFieldValue` events

### ISSUE THREAD

**Issue by souldreamer** [Sawtaytoes/OneForm#16]
Would have probably caught this error with TS, but I mistakenly thought that `updateFieldValue` would only take a `SyntheticEvent` parameter. (which is usually true, but there are special cases -- for example I'm currently working on wrapping an `InputNumber` component whose value has to be numeric, but the input text is actually a formatted string, so can't use the original event; I could patch the event itself, but I should ideally just need to send the value onwards)

Anywho, the first check you do in `updateFieldValue` is:
```typescript
if (typeof event !== 'object' || !('target' in event)) {
```

The issue is that you don't do a null-check before that `in` operator so it fails big-time for `null` values 😅
I'll PR this in a moment (along with updates to the typings to allow non-`SyntheticEvent` parameters to `updateFieldValue`)

**Comment by Sawtaytoes** [comment]
Yep. We had a situation at work where an `onChange` was passing some funky object, not a standard React or JS event.
