### ISSUE TITLE
Reset values

### ISSUE THREAD

**Issue by rogreyroom** [Sawtaytoes/OneForm#20]
Hi,
I'm playing around with OneForm and it is great 👍 

I don't get how it should work (resetting form values I mean) below example from the playground.
```js
...
const formSubmitted = useCallback(({ registeredValues }) => {
    //alert(JSON.stringify(registeredValues, null, 2));
    const values = {}
  }, []);
...
```
In the doc's you can find:
 - To reset all form values after submitting successfully, just pass {} to values

How should I do this the right way?

**Comment by Sawtaytoes** [comment]
I see what you're doing. You'll want to have a separate variable for it and pass it into `OneForm` when you're done.

```js
const [values, setValues] = useState()

const formSubmitted = useCallback(({ registeredValues }) => {
    //alert(JSON.stringify(registeredValues, null, 2));
    setValues({})
  }, []);

return <OneForm values={values}>
// ...
```
