### ISSUE TITLE
Linking the github repo from npm or docs 

### ISSUE THREAD

**Issue by StitiFatah** [Sawtaytoes/OneForm#21]
Hi, 
I can't seem to find the link to this repo either from npm (missing in the right section) https://www.npmjs.com/package/@oneform/react or even from the docs https://docs.oneform.dev/

**Comment by Sawtaytoes** [comment]
That's strange. I can add it to the docs site, but I'm wondering why it doesn't show up on npm. It's possible I'm missing the repo line in `package.json`.

**Comment by Sawtaytoes** [comment]
Fixed in 2.0.1!
![image](https://user-images.githubusercontent.com/3948069/162374483-ea6467a1-accb-4ec9-aa72-90c925310ad8.png)
